export const START_GET_PRODUCT = 'START_GET_PRODUCT';
export const STORE_PRODUCT = 'STORE_PRODUCT';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const END_GET_PRODUCT = 'END_GET_PRODUCT';